import { useState, useRef } from 'react';
import Head from 'next/head';

export default function Accessibility() {
  const [formErrors, setFormErrors] = useState({});
  const emailRef = useRef(null);
  const descRef = useRef(null);

  const validateForm = () => {
    const errors = {};
    const email = emailRef.current?.value.trim();
    const desc = descRef.current?.value.trim();

    if (!email) {
      errors.email = 'Please enter your email address.';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      errors.email = 'Please enter a valid email address.';
    }

    if (!desc) {
      errors.description = 'Please describe the accessibility issue.';
    }

    return errors;
  };

  const handleSubmit = (e) => {
    const errors = validateForm();
    if (Object.keys(errors).length > 0) {
      e.preventDefault();
      setFormErrors(errors);
      // Focus the first field with an error
      if (errors.email) {
        emailRef.current?.focus();
      } else if (errors.description) {
        descRef.current?.focus();
      }
    }
  };

  const clearError = (field) => {
    if (formErrors[field]) {
      setFormErrors(prev => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <>
      <Head>
        <title>Accessibility Statement — Abraham Nemeth Society for Accessible Algorithmics e.V.</title>
        <meta name="description" content="Accessibility statement, feedback process, and compliance monitoring" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="page">
        <a href="#main-content" className="skip-link">Skip to main content</a>

        <header className="letterhead">
          <nav className="letterhead-inner" aria-label="Service">
            <h1 className="org-name">Abraham Nemeth Society for Accessible Algorithmics e.V.</h1>
            <div className="service-title">Web Accessibility Audit Service</div>
          </nav>
        </header>

        <main className="acc-main" id="main-content">
          <div className="acc-content">
            <h1>Accessibility Statement</h1>

            <section aria-labelledby="statement-heading">
              <h2 id="statement-heading">Commitment to Accessibility</h2>
              <p>
                Abraham Nemeth Society for Accessible Algorithmics e.V. is
                committed to ensuring digital accessibility for people with disabilities. This website strives
                to be <strong>WCAG 2.1 AA</strong> compliant in accordance with the European Accessibility Act
                (EAA) and EN 301 549.
              </p>
              <p>
                <strong>Compliance level:</strong> This website is <strong>partially compliant</strong> with
                WCAG 2.1 Level AA. Partial compliance means that some parts of the content do not yet fully
                conform to the accessibility standard.
              </p>
              <p>
                <time dateTime="2026-02-23">Last updated: 23 February 2026</time>
              </p>

              <h3 id="known-issues">Known Issues</h3>
              <ul>
                <li>Some third-party embedded content may not meet all accessibility requirements.</li>
                <li>PDF reports generated by the scanner are being improved for screen reader compatibility.</li>
              </ul>
            </section>

            <section aria-labelledby="contact-heading">
              <h2 id="contact-heading">Contact Mechanism</h2>
              <p>
                If you encounter any accessibility barriers on this website, please contact us using one of the
                following methods. We provide multiple contact channels to ensure everyone can reach us.
              </p>
              <dl className="acc-contact-list">
                <dt>Email</dt>
                <dd><a href="mailto:accessibility@placeholder.org">accessibility@placeholder.org</a></dd>
                <dt>Phone</dt>
                <dd><a href="tel:+4930000000000">+49 30 000 000 000</a></dd>
              </dl>
              <p>
                <strong>Response time:</strong> We will respond within 5 business days of receiving your message.
              </p>
            </section>

            <section aria-labelledby="feedback-heading">
              <h2 id="feedback-heading">Accessibility Feedback Process</h2>
              <p>
                We welcome your feedback on the accessibility of this website. If you would like to
                report an accessibility issue, report a problem, or provide general accessibility feedback,
                please use the form below or contact us directly.
              </p>
              <p>
                <strong>Response commitment:</strong> We reply within 5 business days and will work to resolve
                reported issues promptly.
              </p>

              <form
                className="acc-feedback-form"
                action="mailto:accessibility@placeholder.org"
                method="POST"
                encType="text/plain"
                onSubmit={handleSubmit}
                noValidate
              >
                <fieldset>
                  <legend>Report an Accessibility Issue</legend>

                  {Object.keys(formErrors).length > 0 && (
                    <p className="error-text" role="alert">
                      <strong>Error:</strong> Please correct the highlighted fields below.
                    </p>
                  )}

                  <div className="acc-field">
                    <label htmlFor="feedback-name">Your name</label>
                    <input type="text" id="feedback-name" name="name" autoComplete="name" />
                  </div>

                  <div className="acc-field">
                    <label htmlFor="feedback-email">
                      Your email <span className="required-indicator" aria-hidden="true">*</span>
                      <span className="sr-only">(required)</span>
                    </label>
                    <input
                      ref={emailRef}
                      type="email"
                      id="feedback-email"
                      name="email"
                      aria-required="true"
                      aria-invalid={formErrors.email ? 'true' : undefined}
                      aria-describedby={formErrors.email ? 'feedback-email-error' : undefined}
                      autoComplete="email"
                      onChange={() => clearError('email')}
                    />
                    {formErrors.email && (
                      <p className="error-text" id="feedback-email-error">{formErrors.email}</p>
                    )}
                  </div>

                  <div className="acc-field">
                    <label htmlFor="feedback-url">Page URL where you found the issue</label>
                    <input type="url" id="feedback-url" name="url" autoComplete="url" />
                  </div>

                  <div className="acc-field">
                    <label htmlFor="feedback-description">
                      Describe the accessibility issue <span className="required-indicator" aria-hidden="true">*</span>
                      <span className="sr-only">(required)</span>
                    </label>
                    <textarea
                      ref={descRef}
                      id="feedback-description"
                      name="description"
                      rows="5"
                      aria-required="true"
                      aria-invalid={formErrors.description ? 'true' : undefined}
                      aria-describedby={formErrors.description ? 'feedback-desc-error' : undefined}
                      placeholder="Please describe the accessibility barrier you encountered"
                      onChange={() => clearError('description')}
                    />
                    {formErrors.description && (
                      <p className="error-text" id="feedback-desc-error">{formErrors.description}</p>
                    )}
                  </div>

                  <button type="submit" className="submit-btn">Submit Feedback</button>
                </fieldset>
              </form>
            </section>

            <section aria-labelledby="monitoring-heading">
              <h2 id="monitoring-heading">Compliance Monitoring</h2>
              <p>
                <strong>Monitoring procedures:</strong> We conduct accessibility monitoring through a combination
                of automated testing, manual review, and user feedback analysis.
              </p>
              <p>
                <strong>Regular audits:</strong> Quarterly audit of automated scan results ensures ongoing
                compliance with WCAG 2.1 Level AA and EN 301 549 requirements.
              </p>
              <p>
                <strong>Issue tracking:</strong> Accessibility issues are tracked via GitHub Issues with
                dedicated labels for severity and WCAG criterion.
              </p>
              <p>
                <strong>User feedback integration:</strong> User feedback is reviewed and integrated into
                our development cycle on a rolling basis.
              </p>
              <p>
                <strong>Continuous improvement:</strong> Continuous improvement is guided by our accessibility
                improvement roadmap, which is reviewed and updated quarterly.
              </p>
              <p>
                <strong>Audit schedule:</strong> Annual audit by external assessor, quarterly automated scans,
                and ad-hoc reviews for significant content changes.
              </p>
            </section>

            <p className="acc-back">
              <a href="/">Back to audit service</a>
            </p>
          </div>
        </main>

        <footer className="footer">
          <p>Abraham Nemeth Society for Accessible Algorithmics e.V. — {new Date().getFullYear()}</p>
          <p><a href="/accessibility">Accessibility</a></p>
        </footer>
      </div>
    </>
  );
}
